const ERROR_CODES = {
  // Common errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Auth errors
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  RESET_TOKEN_EXPIRED: 'RESET_TOKEN_EXPIRED',

  // Email errors
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',

  // Court errors
  COURT_NOT_FOUND: 'COURT_NOT_FOUND',
  COURT_REQUIRED_FIELDS: 'COURT_REQUIRED_FIELDS',
  NO_CHANGES: 'NO_CHANGES',

  // Booking errors
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  BOOKING_CONFLICT: 'BOOKING_CONFLICT',
  BOOKING_ALREADY_PAID: 'BOOKING_ALREADY_PAID',
  INVALID_TIME_SLOT: 'INVALID_TIME_SLOT',

  // Payment errors
  INVALID_SIGNATURE: 'INVALID_SIGNATURE',
  PAYMENT_NOT_COMPLETED: 'PAYMENT_NOT_COMPLETED',

  // User errors
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // Statistics errors
  STATISTICS_FETCH_FAILED: 'STATISTICS_FETCH_FAILED',
  STATISTICS_EXPORT_FAILED: 'STATISTICS_EXPORT_FAILED',
};

module.exports = ERROR_CODES;
